spring.application.name=Parcial

# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A SUPABASE (POSTGRESQL) - CLÍNICA
# ===================================================================

# URL JDBC exacta para tu proyecto en Supabase (Puerto estable 5432)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require

# Tu usuario único de base de datos basado en tu Project ID
spring.datasource.username=postgres.uledqvmrhckvtpoxtqst

# ⚠️ REEMPLAZA ESTO CON LA CONTRASEÑA QUE CREASTE AL GENERAR EL PROYECTO EN SUPABASE
spring.datasource.password=Orfa73082087

# Driver de conexión nativo de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA (Capa de Infraestructura)
# ===================================================================

# Dialecto específico para procesar consultas en PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' creará automáticamente las tablas en Supabase según nuestras clases @Entity
spring.jpa.hibernate.ddl-auto=update

# Muestra y formatea las consultas SQL en la consola (Excelente para tu video de YouTube)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true