spring.application.name=Parcial

# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A SUPABASE (POOLER TRADUCIDO A JDBC)
# ===================================================================

# 1. Agregamos el prefijo 'jdbc:' y conservamos el host correcto 'aws-1-us-east-2'
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require

# 2. Tu usuario compuesto obligatorio para el Pooler
spring.datasource.username=postgres.uledqvmrhckvtpoxtqst

# 3. Tu contraseña
spring.datasource.password=Orfa73082087

# Driver nativo de conexión
spring.datasource.driver-class-name=org.postgresql.Driver
# ===================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA (Capa de Infraestructura)
# ===================================================================

# Dialecto específico para procesar consultas en PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' creará automáticamente las tablas en Supabase según nuestras clases @Entity
spring.jpa.hibernate.ddl-auto=update

# Muestra y formatea las consultas SQL en la consola (Excelente para tu video de YouTube)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true